version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: internshipdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d internshipdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - internship_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  webapp:
    build:
      context: .
      dockerfile: InternAccounting/Docker/Dockerfile
    container_name: internship_webapp
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=user;Password=password;Database=internshipdb;TrustServerCertificate=true
    networks:
      - internship_network
    
    restart: always
    links:
      - postgres

volumes:
  pg_data:

networks:
  internship_network:
    driver: bridge